# Site settings
title: reStart
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Heo JaeSeong
user_description: Soccer, Developer, Etc 
user_title: Software Developer
email: bboroccu@gmail.com
twitter_username: 
github_username:  bboroccu
gplus_username:  bboroccu
facebook_username: bboroccu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
