# Site settings
name: 언제나 처음처럼
email: bboroccu@gmail.com
author: 허재성
url: 
resume_site: 
github: https://bboroccu.github.io
baseurl: ""
description: 개발블러그
meta_description: 개발블러그
motto: 즐거운 세상
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bboroccu

# Build settings
markdown: kramdown

baidu_analysis: 

